version: '3'

services:

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: TokyoJoe138!
        
      ports:
        - 8080:8080
      entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
